import socket
import time
import sys

if len(sys.argv) < 4:
    print(f"Usage: {sys.argv[0]} <node_list[0]> <node_list[1]> <node_list[2]>")
    sys.exit(1)

print(f"\nBus online.\nDestination RSU: {sys.argv[3]}\n")

print(f"Node list generated by GPS: {sys.argv[1]}, {sys.argv[2]}, {sys.argv[3]}\n")

# need to know hostname of node.py using hostname -I
# need different port numbers for each
if sys.argv[2] == "A":
    host = "10.35.70.4"
    port = 33500    
if sys.argv[2] == "B":
    host = "10.35.70.4"
    port = 33501
if sys.argv[2] == "C":
    host = "10.35.70.4"
    port = 33502    
if sys.argv[2] == "D":
    host = "10.35.70.4"
    port = 33503  
if sys.argv[2] == "E":
    host = "10.35.70.4"
    port = 33504

serverAddressPort = (host, port)
buffer = 1024
i = 0
finished = False

# Bus acquires the address and port of the next RSU in its node list from a database
def node_ip_address(node):
    return ("127.0.0.1", 65432)

# ETA calculating algorithm will be implemented here
def return_eta():
    return(120)

# Create a UDP socket at client side
UDPClientSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)

# Generate the node list that the EV needs to contact
node_list = [sys.argv[1], sys.argv[2], sys.argv[3], "/"]

# Send to RSU using created UDP socket
while not finished:

    eta = return_eta()
    eta = eta - i # this is simply to simulate the ETA reducing over time as the EV gets closer

    print(f"Sending ETA to RSU {sys.argv[2]}: {eta}")

    converted_eta = str(eta)

    converted_node_list = " ".join(node_list) 
    msgFromClient = converted_node_list + converted_eta
    bytesToSend = str.encode(msgFromClient)
    UDPClientSocket.sendto(bytesToSend, serverAddressPort)
    
    time.sleep(3)
    i = i + 10 
    if eta < 10: # if the EV is within 10 seconds of the light, stop sending telemetry
        finished = True

print("\nFinishing connection")
msgFromServer = UDPClientSocket.recvfrom(buffer)

msg = "Message from RSU {}".format(msgFromServer[0])

print(msg)